import type { RequirementItem, SpecProject } from './types'

function evidenceReference(project: SpecProject, evidenceId: string): string {
  const evidence = project.evidence.find((item) => item.id === evidenceId)
  const source = evidence ? project.sources.find((item) => item.id === evidence.sourceId) : undefined
  if (!evidence) return `Unknown evidence (${evidenceId})`
  return `“${evidence.quote}” — ${source?.title ?? 'Unknown source'}, line ${evidence.lineStart}`
}

function acceptanceMarkdown(requirement: RequirementItem): string {
  return requirement.criteria.map((criterion) => [
    `- **Given** ${criterion.given}`,
    `  **When** ${criterion.when}`,
    `  **Then** ${criterion.then}`,
  ].join('\n')).join('\n')
}

export function exportPrd(project: SpecProject): string {
  const requirements = project.requirements.map((requirement) => `### ${requirement.id} · ${requirement.title}

**Priority:** ${requirement.priority}  
**Status:** ${requirement.status}

${requirement.statement}

#### Acceptance criteria

${acceptanceMarkdown(requirement)}

#### Evidence

${requirement.evidenceIds.map((id) => `- ${evidenceReference(project, id)}`).join('\n')}`).join('\n\n---\n\n')

  return `# ${project.name} · Product Requirements Document

Generated by SpecLoop. Every requirement below preserves its source references.

## Product decisions

${project.decisions.map((decision) => `- **${decision.status}** ${decision.statement}\n  - Rationale: ${decision.rationale}`).join('\n') || '- No explicit decisions recorded.'}

## Requirements

${requirements}
`
}

export function exportUserStories(project: SpecProject): string {
  return `# ${project.name} · User Stories

${project.requirements.map((requirement) => `## ${requirement.priority} · ${requirement.title}

As a product team member, I want ${requirement.statement.replace(/^系统必须|^系统应当|^用户必须/u, '')} so that the requirement can be implemented and verified with its original context.

### Acceptance criteria

${acceptanceMarkdown(requirement)}

### Source evidence

${requirement.evidenceIds.map((id) => `- ${evidenceReference(project, id)}`).join('\n')}`).join('\n\n---\n\n')}
`
}

export function exportGithubIssues(project: SpecProject): string {
  return project.requirements.map((requirement) => `---
title: "[${requirement.priority}] ${requirement.title}"
labels: ["requirement", "${requirement.priority.toLowerCase()}"]
---

## Requirement

${requirement.statement}

## Acceptance criteria

${acceptanceMarkdown(requirement)}

## Evidence

${requirement.evidenceIds.map((id) => `- ${evidenceReference(project, id)}`).join('\n')}

## Traceability

- SpecLoop requirement ID: \`${requirement.id}\`
- Decision IDs: ${requirement.decisionIds.map((id) => `\`${id}\``).join(', ') || 'None'}
`).join('\n\n')
}

export function downloadMarkdown(filename: string, content: string): void {
  const blob = new Blob([content], { type: 'text/markdown;charset=utf-8' })
  const url = URL.createObjectURL(blob)
  const anchor = document.createElement('a')
  anchor.href = url
  anchor.download = filename
  anchor.click()
  URL.revokeObjectURL(url)
}

